---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - rag.opendatahub.io
  resources:
  - milvuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rag.opendatahub.io
  resources:
  - milvuses/finalizers
  verbs:
  - update
- apiGroups:
  - rag.opendatahub.io
  resources:
  - milvuses/status
  verbs:
  - get
  - patch
  - update
